### ISSUE TITLE
训练最后会crash

### ISSUE THREAD

**Issue by xiazhenyz** [hzwer/arXiv2020-RIFE#96]
感谢楼主的辛苦付出，测了几段视频，大运动效果和纹理很稳定，重影很少。
所以尝试复现一下效果，用了你给的100个数据做了一下测试，跑20个epoch，跑完最后会crash
机器是P40，双卡。
脚本是：
`python3 -u -m torch.distributed.launch --nproc_per_node=1 train.py --local_rank=0`
所有输出的日志：

nohup: ignoring input
457012eb-9ba5-4d55-9bbe-a3f39dfe66c5:82576:82576 [0] NCCL INFO Bootstrap : Using [0]eth1:9.73.145.207<0>
457012eb-9ba5-4d55-9bbe-a3f39dfe66c5:82576:82576 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).

457012eb-9ba5-4d55-9bbe-a3f39dfe66c5:82576:82576 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
457012eb-9ba5-4d55-9bbe-a3f39dfe66c5:82576:82576 [0] NCCL INFO NET/Socket : Using [0]eth1:9.73.145.207<0>
NCCL version 2.4.8+cuda10.1
457012eb-9ba5-4d55-9bbe-a3f39dfe66c5:82576:82608 [0] NCCL INFO Setting affinity for GPU 0 to 01f000,0000001f
457012eb-9ba5-4d55-9bbe-a3f39dfe66c5:82576:82608 [0] NCCL INFO Using 256 threads, Min Comp Cap 6, Trees enabled up to size -2
457012eb-9ba5-4d55-9bbe-a3f39dfe66c5:82576:82608 [0] NCCL INFO comm 0x7f8880001a40 rank 0 nranks 1 cudaDev 0 nvmlDev 0 - Init COMPLETE
------------this evaluating is start....--------
/tools/conda/envs/rife/lib/python3.9/site-packages/torch/nn/functional.py:3000: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and uses scale_factor directly, instead of relying on the computed output size. If you wish to keep the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
eval time: 4.768563508987427
------------this evaluating is end--------
training...
running epoch is 0 
epoch:0 0/3 time:0.31+2.41 loss_l1:6.6461e-02
epoch:0 4/3 time:0.00+0.49 loss_l1:6.6527e-02
epoch:0 2/3 time:0.88+0.39 loss_l1:6.1271e-02
------------last barrier is end....--------
running epoch is 1 
epoch:1 0/3 time:0.47+0.38 loss_l1:6.6090e-02
epoch:1 1/3 time:0.00+0.38 loss_l1:6.4821e-02
epoch:1 2/3 time:0.00+0.38 loss_l1:5.8615e-02
------------last barrier is end....--------
running epoch is 2 
epoch:2 0/3 time:0.47+0.38 loss_l1:6.2020e-02
epoch:2 1/3 time:0.00+0.37 loss_l1:6.0823e-02
epoch:2 2/3 time:0.00+0.37 loss_l1:6.3036e-02
------------last barrier is end....--------
running epoch is 3 
epoch:3 0/3 time:0.48+0.37 loss_l1:6.6802e-02
epoch:3 1/3 time:0.00+0.37 loss_l1:6.0749e-02
epoch:3 2/3 time:0.00+0.37 loss_l1:5.8643e-02
------------last barrier is end....--------
running epoch is 4 
epoch:4 0/3 time:0.45+0.38 loss_l1:6.1430e-02
epoch:4 1/3 time:0.00+0.37 loss_l1:5.8594e-02
epoch:4 2/3 time:0.00+0.37 loss_l1:5.8876e-02
------------this evaluating is start....--------
eval time: 1.697829008102417
------------this evaluating is end--------
------------last barrier is end....--------
running epoch is 5 
epoch:5 0/3 time:2.19+0.39 loss_l1:6.0860e-02
epoch:5 1/3 time:0.00+0.39 loss_l1:5.6333e-02
epoch:5 2/3 time:0.00+0.39 loss_l1:5.6805e-02
------------last barrier is end....--------
running epoch is 6 
epoch:6 0/3 time:0.49+0.39 loss_l1:5.8091e-02
epoch:6 1/3 time:0.00+0.39 loss_l1:5.8843e-02
epoch:6 2/3 time:0.00+0.38 loss_l1:5.5708e-02
------------last barrier is end....--------
running epoch is 7 
epoch:7 0/3 time:0.45+0.37 loss_l1:5.5774e-02
epoch:7 1/3 time:0.00+0.37 loss_l1:5.7322e-02
epoch:7 2/3 time:0.00+0.37 loss_l1:5.1374e-02
------------last barrier is end....--------
running epoch is 8 
epoch:8 0/3 time:0.49+0.39 loss_l1:5.5491e-02
epoch:8 1/3 time:0.00+0.39 loss_l1:5.4187e-02
epoch:8 2/3 time:0.00+0.39 loss_l1:4.9916e-02
------------last barrier is end....--------
running epoch is 9 
epoch:9 0/3 time:0.52+0.37 loss_l1:5.7686e-02
epoch:9 1/3 time:0.00+0.37 loss_l1:5.2956e-02
epoch:9 2/3 time:0.00+0.37 loss_l1:4.9873e-02
------------this evaluating is start....--------
eval time: 1.6385705471038818
------------this evaluating is end--------
------------last barrier is end....--------
running epoch is 10 
epoch:10 0/3 time:2.12+0.37 loss_l1:5.2009e-02
epoch:10 1/3 time:0.00+0.37 loss_l1:4.7775e-02
epoch:10 2/3 time:0.00+0.37 loss_l1:5.0613e-02
------------last barrier is end....--------
running epoch is 11 
epoch:11 0/3 time:0.51+0.37 loss_l1:4.8291e-02
epoch:11 1/3 time:0.00+0.37 loss_l1:4.5139e-02
epoch:11 2/3 time:0.00+0.37 loss_l1:4.7583e-02
------------last barrier is end....--------
running epoch is 12 
epoch:12 0/3 time:0.48+0.37 loss_l1:4.8362e-02
epoch:12 1/3 time:0.00+0.37 loss_l1:4.9962e-02
epoch:12 2/3 time:0.00+0.37 loss_l1:4.7941e-02
------------last barrier is end....--------
running epoch is 13 
epoch:13 0/3 time:0.49+0.38 loss_l1:4.6211e-02
epoch:13 1/3 time:0.00+0.37 loss_l1:4.7942e-02
epoch:13 2/3 time:0.00+0.37 loss_l1:4.4998e-02
------------last barrier is end....--------
running epoch is 14 
epoch:14 0/3 time:0.48+0.38 loss_l1:4.4784e-02
epoch:14 1/3 time:0.00+0.37 loss_l1:4.7616e-02
epoch:14 2/3 time:0.00+0.37 loss_l1:4.3033e-02
------------this evaluating is start....--------
eval time: 1.6448850631713867
------------this evaluating is end--------
------------last barrier is end....--------
running epoch is 15 
epoch:15 0/3 time:2.13+0.38 loss_l1:4.2588e-02
epoch:15 1/3 time:0.00+0.37 loss_l1:4.5357e-02
epoch:15 2/3 time:0.00+0.38 loss_l1:4.2175e-02
------------last barrier is end....--------
running epoch is 16 
epoch:16 0/3 time:0.61+0.39 loss_l1:4.3911e-02
epoch:16 1/3 time:0.00+0.37 loss_l1:4.1421e-02
epoch:16 2/3 time:0.00+0.37 loss_l1:4.3421e-02
------------last barrier is end....--------
running epoch is 17 
epoch:17 0/3 time:0.47+0.38 loss_l1:4.3027e-02
epoch:17 1/3 time:0.00+0.37 loss_l1:4.2315e-02
epoch:17 2/3 time:0.00+0.37 loss_l1:4.3238e-02
------------last barrier is end....--------
running epoch is 18 
epoch:18 0/3 time:0.49+0.38 loss_l1:4.0845e-02
epoch:18 1/3 time:0.00+0.37 loss_l1:3.9075e-02
epoch:18 2/3 time:0.00+0.37 loss_l1:4.0612e-02
------------last barrier is end....--------
running epoch is 19 
epoch:19 0/3 time:0.47+0.38 loss_l1:4.0664e-02
epoch:19 1/3 time:0.00+0.37 loss_l1:4.0039e-02
epoch:19 2/3 time:0.00+0.37 loss_l1:4.1695e-02
------------this evaluating is start....--------
eval time: 1.6566226482391357
------------this evaluating is end--------
------------last barrier is end....--------
terminate called without an active exception
terminate called without an active exception
Traceback (most recent call last):
  File "/tools/conda/envs/rife/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tools/conda/envs/rife/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tools/conda/envs/rife/lib/python3.9/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/tools/conda/envs/rife/lib/python3.9/site-packages/torch/distributed/launch.py", line 256, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/tools/conda/envs/rife/bin/python3', '-u', 'train.py', '--local_rank=0', '--local_rank=0']' died with <Signals.SIGABRT: 6>.

跑完最后一个epoch，保存了模型，处理完dist.barrier()后按道理应该就结束了，但不知道为什么会crash，看起来和分布式有关，不知道楼主有什么经验吗？感谢感谢

**Comment by hzwer** [comment]
按理说你需要 --worldsize=2 才能训起来

**Comment by xiazhenyz** [comment]
> 按理说你需要 --worldsize=2 才能训起来

这个报错解决了，我意外的使用raft的环境最后没有出现crash，这个有点奇怪，我还不知道是什么问题。
我设置的world_size = 1, local_rank=0
这里有另外一个问题：训练保存的三个模型大小和你提供的大小不一致，如下图所示，这是哪里导致的呢？
![image](https://user-images.githubusercontent.com/22024498/105483744-43d17a00-5ce5-11eb-930c-864d24431b83.png)

**Comment by xiazhenyz** [comment]
如果测试模型，会报以下错误
`Traceback (most recent call last):
  File "/RIFE/inference_video.py", line 78, in <module>
    model.load_model('./train_log', -1)
  File "/RIFE/model/RIFE_HD.py", line 178, in load_model
    self.flownet.load_state_dict(
  File "/tools/conda/envs/rife/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for IFNet:
        Missing key(s) in state_dict: "block0.conv0.0.weight", "block0.conv0.1.weight", "block0.conv0.1.bias", "block0.conv0.1.running_mean", "block0.conv0.1.running_var", "block0.conv0.2.weight", "block0.res0.conv1.0.weight", "block0.res0.conv1.1.weight", "block0.res0.conv1.1.bias", "block0.res0.conv1.1.running_mean", "block0.res0.conv1.1.running_var", "block0.res0.conv1.2.weight", "block0.res0.conv2.0.weight", "block0.res0.conv2.1.weight", "block0.res0.conv2.1.bias", "block0.res0.conv2.1.running_mean", "block0.res0.conv2.1.running_var", "block0.res0.relu1.weight", "block0.res0.relu2.weight", "block0.res0.fc1.weight", "block0.res0.fc2.weight", "block0.res1.conv1.0.weight", "block0.res1.conv1.1.weight", "block0.res1.conv1.1.bias", "block0.res1.conv1.1.running_mean", "block0.res1.conv1.1.running_var", "block0.res1.conv1.2.weight", "block0.res1.conv2.0.weight", "block0.res1.conv2.1.weight", "block0.res1.conv2.1.bias", "block0.res1.conv2.1.running_mean", "block0.res1.conv2.1.running_var", "block0.res1.relu1.weight", "block0.res1.relu2.weight", "block0.res1.fc1.weight", "block0.res1.fc2.weight", "block0.res2.conv1.0.weight", "block0.res2.conv1.1.weight", "block0.res2.conv1.1.bias", "block0.res2.conv1.1.running_mean", "block0.res2.conv1.1.running_var", "block0.res2.conv1.2.weight", "block0.res2.conv2.0.weight", "block0.res2.conv2.1.weight", "block0.res2.conv2.1.bias", "block0.res2.conv2.1.running_mean", "block0.res2.conv2.1.running_var", "block0.res2.relu1.weight", "block0.res2.relu2.weight", "block0.res2.fc1.weight", "block0.res2.fc2.weight", "block0.res3.conv1.0.weight", "block0.res3.conv1.1.weight", "block0.res3.conv1.1.bias", "block0.res3.conv1.1.running_mean", "block0.res3.conv1.1.running_var", "block0.res3.conv1.2.weight", "block0.res3.conv2.0.weight", "block0.res3.conv2.1.weight", "block0.res3.conv2.1.bias", "block0.res3.conv2.1.running_mean", "block0.res3.conv2.1.running_var", "block0.res3.relu1.weight", "block0.res3.relu2.weight", "block0.res3.fc1.weight", "block0.res3.fc2.weight", "block0.res4.conv1.0.weight", "block0.res4.conv1.1.weight", "block0.res4.conv1.1.bias", "block0.res4.conv1.1.running_mean", "block0.res4.conv1.1.running_var", "block0.res4.conv1.2.weight", "block0.res4.conv2.0.weight", "block0.res4.conv2.1.weight", "block0.res4.conv2.1.bias", "block0.res4.conv2.1.running_mean", "block0.res4.conv2.1.running_var", "block0.res4.relu1.weight", "block0.res4.relu2.weight", "block0.res4.fc1.weight", "block0.res4.fc2.weight", "block0.res5.conv1.0.weight", "block0.res5.conv1.1.weight", "block0.res5.conv1.1.bias", "block0.res5.conv1.1.running_mean", "block0.res5.conv1.1.running_var", "block0.res5.conv1.2.weight", "block0.res5.conv2.0.weight", "block0.res5.conv2.1.weight", "block0.res5.conv2.1.bias", "block0.res5.conv2.1.running_mean", "block0.res5.conv2.1.running_var", "block0.res5.relu1.weight", "block0.res5.relu2.weight", "block0.res5.fc1.weight", "block0.res5.fc2.weight", "block0.conv1.weight", "block0.conv1.bias", "block1.conv0.0.weight", "block1.conv0.1.weight", "block1.conv0.1.bias", "block1.conv0.1.running_mean", "block1.conv0.1.running_var", "block1.conv0.2.weight", "block1.res0.conv1.0.weight", "block1.res0.conv1.1.weight", "block1.res0.conv1.1.bias", "block1.res0.conv1.1.running_mean", "block1.res0.conv1.1.running_var", "block1.res0.conv1.2.weight", "block1.res0.conv2.0.weight", "block1.res0.conv2.1.weight", "block1.res0.conv2.1.bias", "block1.res0.conv2.1.running_mean", "block1.res0.conv2.1.running_var", "block1.res0.relu1.weight", "block1.res0.relu2.weight", "block1.res0.fc1.weight", "block1.res0.fc2.weight", "block1.res1.conv1.0.weight", "block1.res1.conv1.1.weight", "block1.res1.conv1.1.bias", "block1.res1.conv1.1.running_mean", "block1.res1.conv1.1.running_var", "block1.res1.conv1.2.weight", "block1.res1.conv2.0.weight", "block1.res1.conv2.1.weight", "block1.res1.conv2.1.bias", "block1.res1.conv2.1.running_mean", "block1.res1.conv2.1.running_var", "block1.res1.relu1.weight", "block1.res1.relu2.weight", "block1.res1.fc1.weight", "block1.res1.fc2.weight", "block1.res2.conv1.0.weight", "block1.res2.conv1.1.weight", "block1.res2.conv1.1.bias", "block1.res2.conv1.1.running_mean", "block1.res2.conv1.1.running_var", "block1.res2.conv1.2.weight", "block1.res2.conv2.0.weight", "block1.res2.conv2.1.weight", "block1.res2.conv2.1.bias", "block1.res2.conv2.1.running_mean", "block1.res2.conv2.1.running_var", "block1.res2.relu1.weight", "block1.res2.relu2.weight", "block1.res2.fc1.weight", "block1.res2.fc2.weight", "block1.res3.conv1.0.weight", "block1.res3.conv1.1.weight", "block1.res3.conv1.1.bias", "block1.res3.conv1.1.running_mean", "block1.res3.conv1.1.running_var", "block1.res3.conv1.2.weight", "block1.res3.conv2.0.weight", "block1.res3.conv2.1.weight", "block1.res3.conv2.1.bias", "block1.res3.conv2.1.running_mean", "block1.res3.conv2.1.running_var", "block1.res3.relu1.weight", "block1.res3.relu2.weight", "block1.res3.fc1.weight", "block1.res3.fc2.weight", "block1.res4.conv1.0.weight", "block1.res4.conv1.1.weight", "block1.res4.conv1.1.bias", "block1.res4.conv1.1.running_mean", "block1.res4.conv1.1.running_var", "block1.res4.conv1.2.weight", "block1.res4.conv2.0.weight", "block1.res4.conv2.1.weight", "block1.res4.conv2.1.bias", "block1.res4.conv2.1.running_mean", "block1.res4.conv2.1.running_var", "block1.res4.relu1.weight", "block1.res4.relu2.weight", "block1.res4.fc1.weight", "block1.res4.fc2.weight", "block1.res5.conv1.0.weight", "block1.res5.conv1.1.weight", "block1.res5.conv1.1.bias", "block1.res5.conv1.1.running_mean", "block1.res5.conv1.1.running_var", "block1.res5.conv1.2.weight", "block1.res5.conv2.0.weight", "block1.res5.conv2.1.weight", "block1.res5.conv2.1.bias", "block1.res5.conv2.1.running_mean", "block1.res5.conv2.1.running_var", "block1.res5.relu1.weight", "block1.res5.relu2.weight", "block1.res5.fc1.weight", "block1.res5.fc2.weight", "block1.conv1.weight", "block1.conv1.bias", "block2.conv0.0.weight", "block2.conv0.1.weight", "block2.conv0.1.bias", "block2.conv0.1.running_mean", "block2.conv0.1.running_var", "block2.conv0.2.weight", "block2.res0.conv1.0.weight", "block2.res0.conv1.1.weight", "block2.res0.conv1.1.bias", "block2.res0.conv1.1.running_mean", "block2.res0.conv1.1.running_var", "block2.res0.conv1.2.weight", "block2.res0.conv2.0.weight", "block2.res0.conv2.1.weight", "block2.res0.conv2.1.bias", "block2.res0.conv2.1.running_mean", "block2.res0.conv2.1.running_var", "block2.res0.relu1.weight", "block2.res0.relu2.weight", "block2.res0.fc1.weight", "block2.res0.fc2.weight", "block2.res1.conv1.0.weight", "block2.res1.conv1.1.weight", "block2.res1.conv1.1.bias", "block2.res1.conv1.1.running_mean", "block2.res1.conv1.1.running_var", "block2.res1.conv1.2.weight", "block2.res1.conv2.0.weight", "block2.res1.conv2.1.weight", "block2.res1.conv2.1.bias", "block2.res1.conv2.1.running_mean", "block2.res1.conv2.1.running_var", "block2.res1.relu1.weight", "block2.res1.relu2.weight", "block2.res1.fc1.weight", "block2.res1.fc2.weight", "block2.res2.conv1.0.weight", "block2.res2.conv1.1.weight", "block2.res2.conv1.1.bias", "block2.res2.conv1.1.running_mean", "block2.res2.conv1.1.running_var", "block2.res2.conv1.2.weight", "block2.res2.conv2.0.weight", "block2.res2.conv2.1.weight", "block2.res2.conv2.1.bias", "block2.res2.conv2.1.running_mean", "block2.res2.conv2.1.running_var", "block2.res2.relu1.weight", "block2.res2.relu2.weight", "block2.res2.fc1.weight", "block2.res2.fc2.weight", "block2.res3.conv1.0.weight", "block2.res3.conv1.1.weight", "block2.res3.conv1.1.bias", "block2.res3.conv1.1.running_mean", "block2.res3.conv1.1.running_var", "block2.res3.conv1.2.weight", "block2.res3.conv2.0.weight", "block2.res3.conv2.1.weight", "block2.res3.conv2.1.bias", "block2.res3.conv2.1.running_mean", "block2.res3.conv2.1.running_var", "block2.res3.relu1.weight", "block2.res3.relu2.weight", "block2.res3.fc1.weight", "block2.res3.fc2.weight", "block2.res4.conv1.0.weight", "block2.res4.conv1.1.weight", "block2.res4.conv1.1.bias", "block2.res4.conv1.1.running_mean", "block2.res4.conv1.1.running_var", "block2.res4.conv1.2.weight", "block2.res4.conv2.0.weight", "block2.res4.conv2.1.weight", "block2.res4.conv2.1.bias", "block2.res4.conv2.1.running_mean", "block2.res4.conv2.1.running_var", "block2.res4.relu1.weight", "block2.res4.relu2.weight", "block2.res4.fc1.weight", "block2.res4.fc2.weight", "block2.res5.conv1.0.weight", "block2.res5.conv1.1.weight", "block2.res5.conv1.1.bias", "block2.res5.conv1.1.running_mean", "block2.res5.conv1.1.running_var", "block2.res5.conv1.2.weight", "block2.res5.conv2.0.weight", "block2.res5.conv2.1.weight", "block2.res5.conv2.1.bias", "block2.res5.conv2.1.running_mean", "block2.res5.conv2.1.running_var", "block2.res5.relu1.weight", "block2.res5.relu2.weight", "block2.res5.fc1.weight", "block2.res5.fc2.weight", "block2.conv1.weight", "block2.conv1.bias", "block3.conv0.0.weight", "block3.conv0.1.weight", "block3.conv0.1.bias", "block3.conv0.1.running_mean", "block3.conv0.1.running_var", "block3.conv0.2.weight", "block3.res0.conv1.0.weight", "block3.res0.conv1.1.weight", "block3.res0.conv1.1.bias", "block3.res0.conv1.1.running_mean", "block3.res0.conv1.1.running_var", "block3.res0.conv1.2.weight", "block3.res0.conv2.0.weight", "block3.res0.conv2.1.weight", "block3.res0.conv2.1.bias", "block3.res0.conv2.1.running_mean", "block3.res0.conv2.1.running_var", "block3.res0.relu1.weight", "block3.res0.relu2.weight", "block3.res0.fc1.weight", "block3.res0.fc2.weight", "block3.res1.conv1.0.weight", "block3.res1.conv1.1.weight", "block3.res1.conv1.1.bias", "block3.res1.conv1.1.running_mean", "block3.res1.conv1.1.running_var", "block3.res1.conv1.2.weight", "block3.res1.conv2.0.weight", "block3.res1.conv2.1.weight", "block3.res1.conv2.1.bias", "block3.res1.conv2.1.running_mean", "block3.res1.conv2.1.running_var", "block3.res1.relu1.weight", "block3.res1.relu2.weight", "block3.res1.fc1.weight", "block3.res1.fc2.weight", "block3.res2.conv1.0.weight", "block3.res2.conv1.1.weight", "block3.res2.conv1.1.bias", "block3.res2.conv1.1.running_mean", "block3.res2.conv1.1.running_var", "block3.res2.conv1.2.weight", "block3.res2.conv2.0.weight", "block3.res2.conv2.1.weight", "block3.res2.conv2.1.bias", "block3.res2.conv2.1.running_mean", "block3.res2.conv2.1.running_var", "block3.res2.relu1.weight", "block3.res2.relu2.weight", "block3.res2.fc1.weight", "block3.res2.fc2.weight", "block3.res3.conv1.0.weight", "block3.res3.conv1.1.weight", "block3.res3.conv1.1.bias", "block3.res3.conv1.1.running_mean", "block3.res3.conv1.1.running_var", "block3.res3.conv1.2.weight", "block3.res3.conv2.0.weight", "block3.res3.conv2.1.weight", "block3.res3.conv2.1.bias", "block3.res3.conv2.1.running_mean", "block3.res3.conv2.1.running_var", "block3.res3.relu1.weight", "block3.res3.relu2.weight", "block3.res3.fc1.weight", "block3.res3.fc2.weight", "block3.res4.conv1.0.weight", "block3.res4.conv1.1.weight", "block3.res4.conv1.1.bias", "block3.res4.conv1.1.running_mean", "block3.res4.conv1.1.running_var", "block3.res4.conv1.2.weight", "block3.res4.conv2.0.weight", "block3.res4.conv2.1.weight", "block3.res4.conv2.1.bias", "block3.res4.conv2.1.running_mean", "block3.res4.conv2.1.running_var", "block3.res4.relu1.weight", "block3.res4.relu2.weight", "block3.res4.fc1.weight", "block3.res4.fc2.weight", "block3.res5.conv1.0.weight", "block3.res5.conv1.1.weight", "block3.res5.conv1.1.bias", "block3.res5.conv1.1.running_mean", "block3.res5.conv1.1.running_var", "block3.res5.conv1.2.weight", "block3.res5.conv2.0.weight", "block3.res5.conv2.1.weight", "block3.res5.conv2.1.bias", "block3.res5.conv2.1.running_mean", "block3.res5.conv2.1.running_var", "block3.res5.relu1.weight", "block3.res5.relu2.weight", "block3.res5.fc1.weight", "block3.res5.fc2.weight", "block3.conv1.weight", "block3.conv1.bias".`

**Comment by hzwer** [comment]
@xiazhenyz 抱歉忘记回复了
注意一下 inference 用的是 RIFE_HD 模型，和默认的训练模型不是一个模型

**Comment by xiazhenyz** [comment]
> @xiazhenyz 抱歉忘记回复了
> 注意一下 inference 用的是 RIFE_HD 模型，和默认的训练模型不是一个模型

**Comment by xiazhenyz** [comment]
@hzwer 感谢感谢，我修改了inference的模型改成RIFE，同时修改
model.inference(I0, I1, args.UHD)
去掉最后一个参数能正常做inference了。

**Comment by xiazhenyz** [comment]
@hzwer 另外我看其他issue里有提到训练vimeo数据因为太大，通常不能一次加载所有数据，否则会显存不够，所以对训练过程有什么建议吗？谢谢~

**Comment by hzwer** [comment]
如何分布式训练是一个工程问题，不知道在你的环境上应该怎么解决，鉴于图比较小，每次从硬盘读取或许也可以
